name: C++

on: 
  push:
  workflow_dispatch:

jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: install cppunit
      run: sudo apt install -y libcppunit-dev

    - name: configure
      run: ./configure

    - name: make
      run: make

    - name: test cppunit
      run: make test

    - name: Publish unit test results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: '*.xml'
        report_individual_runs: "true"

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: artifact
        path: .

    - name: clean
      run: make clean
      